services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eyedb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:root@db:3306/eyedb
      JWT_SECRET_KEY: "123"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://localhost:5000"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  db_data:
